# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ViewAutoLayou_IB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SQLite.swift', '~> 0.13.0'

end
